name: glottdnn
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pyyaml
  - scikit-learn
  - pytorch>=1.1
  - torchaudio
  - autoconf
  - automake
  - cmake
  - pybind11
  - pytest
  - make
  - cxx-compiler
  - gsl
  - libconfig
  - libsndfile
